export const PHYSICS_CONFIG = Object.freeze({
  // Movement
  DEFAULT_SPEED: 20,
  FRICTION: 0.975,
  MIN_VELOCITY: 0.01,

  // Pathfinding
  PATH_ARRIVAL_THRESHOLD: 0.5,
  PATH_ARRIVAL_MIN: 0.01,
  WALL_BUFFER_MULTIPLIER: 1.5,

  // Destination Scoring (for pathfinding destination selection)
  PATH_PROXIMITY_WEIGHT: 3,
  PROGRESS_WEIGHT: 0.1,
  MIN_SCORE_THRESHOLD: 1.0,

  // Spawning
  POSITION_JITTER: 0.3,

  // Combat
  WALL_COLLISION_THRESHOLD: 0.1,
  KNOCKBACK_FRICTION: 0.92,
  MAX_KNOCKBACK_VELOCITY: 200,
  DEATH_ANIMATION_DURATION: 500,

  // Spatial Partitioning
  SPATIAL_GRID_CELL_SIZE: 100
});
